export { default as HeroSection } from './HeroSection'
export { default as About } from './About'
export { default as WorkGallery } from './WorkGallery'
export { default as FindUs } from './FindUs'
export { default as Services } from './Services'
