export { default as FeaturedPosts } from './FeaturedPosts'
export { default as HeroSection } from './HeroSection'
export { default as About } from './About'
export { default as WorkGallery } from './WorkGallery'
export { default as FindUs } from './FindUs'
