import Head from 'next/head'
import { PostCard, Categories, PostWidget } from '../components'
import { getPosts } from '../services'
import { FeaturedPosts } from '../sections'

// const posts = [
//   {title: 'PHILSCREAM SUPERCHARGED E92 M3', description: 'FUTURE CLASSIC E92 M3'},
//   {title: 'Maksezzy E46 M3', description: 'FUTURE CLASSIC E46 M3'},
//   {title: 'Alpine E36 M3', description: 'FUTURE CLASSIC E36 M3'}
// ];


export default function Home({ posts }) {
  return (
    <div className="container mx-auto px-10 mb-8">
      <Head>
        <title>A Cut Above Autofilm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/star.png" />
      </Head>
      <FeaturedPosts />
      <div className='grid lg:grid-cols-12 grid-cols-1 gap-12'>
        {/* Left Section */}
        <div className='lg:col-span-8 col-span-1'>
          {posts.map((post) => <PostCard post={post.node} key={post.title} />)}
        </div>
        {/* Right Section */}
        <div className='col-span-1 lg:col-span-4'>
            <div className='lg:sticky relative top-8 text-gray-400'>
              <PostWidget />
              <Categories />
            </div>
        </div>
      </div>
    </div>
  )
}

export async function getStaticProps() {
  const posts = (await getPosts()) || []

  return {
    props: { posts }
  }
}